stages:
  - build
  - deploy

variables:
  CI_BUILDER_VERSION: "1"

Build:
  stage: build
  script:
  - ci-builder
  tags:
  except:
  - tags

Deploy:
  when: manual
  stage: deploy
  script:
    - ci-deploy
